llvm: merge CachyOS LLVM builds (llvm, llvm-propeller, llvm-git) (#89)
Co-authored-by: Claude <noreply@anthropic.com>

diff --git a/llvm/PKGBUILD b/llvm/PKGBUILD
--- a/llvm/PKGBUILD
+++ b/llvm/PKGBUILD
@@ -1,133 +1,207 @@
-# Maintainer: Ven0m0
-# Contributor: Peter Jung ptr1337 <admin@ptr1337.dev>
-# Contributor: Evangelos Foutras <foutrelis@archlinux.org>
+# Maintainer: Evangelos Foutras <foutrelis@archlinux.org>
 # Contributor: Jan "heftig" Steffens <jan.steffens@gmail.com>
 
-# Build Profiles:
-# - release: Standard Arch release build.
-# - pgo:     'release' with Profile-Guided Optimization (Full LTO). Slow build, fast binary.
-# - nano:    Minimal build with limited targets (X86;AMDGPU or AArch64;AMDGPU).
-# - mini:    Minimal build with all targets.
-_build_profile=${_build_profile:-nano}
 pkgname=('llvm' 'llvm-libs')
-pkgver=21.1.4
+pkgver=21.1.6
 pkgrel=2
-arch=('x86_64' 'aarch64')
-url='https://llvm.org/'
+arch=('x86_64')
+url="https://llvm.org/"
 license=('Apache-2.0 WITH LLVM-exception')
-depends=('llvm-libs' 'curl' 'perl')
-optdepends=('llvm-propeller: for post-link optimization (requires _build_profile=pgo)')
-makedepends=('cmake' 'ninja' 'zlib' 'zstd' 'curl' 'libffi' 'libedit'
-  'libxml2' 'python-setuptools' 'python-psutil' 'python-sphinx'
-  'python-myst-parser' 'clang' 'lld' 'llvm')
-options=('!lto')
-_source_base="https://github.com/llvm/llvm-project/releases/download/llvmorg-${pkgver}#depth=1"
-source=("$_source_base/llvm-$pkgver.src.tar.xz"{,.sig}
-  "$_source_base/cmake-$pkgver.src.tar.xz"{,.sig}
-  "$_source_base/third-party-$pkgver.src.tar.xz"{,.sig})
-sha256sums=('f311681255deb37f74bbf950a653e9434e7d8383a7b46a603a323c46cd4bf50e'
-  'SKIP'
-  'f4316d84a862ba3023ca1d26bd9c6a995516b4fa028b6fb329d22e24cc6d235e'
-  'SKIP'
-  'ae8658390504e08e464f65ecea838a0584df4734c27cecedfe7eb32780e81564'
-  'SKIP')
-validpgpkeys=('474E22316ABF4785A88C6E8EA2C794A986419D8A'
-  'D574BD5D1D0E98895E3BF90044F2485E45D59042')
+makedepends=('cmake' 'ninja' 'zlib' 'zstd' 'curl' 'libffi' 'libedit' 'libxml2'
+             'python-setuptools' 'python-psutil' 'python-sphinx'
+             'python-myst-parser' 'python-build' 'python-installer' 'python-wheel'
+             'clang' 'lld' 'llvm')
+options=('staticlibs' '!lto') # tools/llvm-shlib/typeids.test fails with LTO
+_source_base=https://github.com/llvm/llvm-project/releases/download/llvmorg-$pkgver
+source=($_source_base/llvm-$pkgver.src.tar.xz{,.sig}
+        $_source_base/cmake-$pkgver.src.tar.xz{,.sig}
+        $_source_base/third-party-$pkgver.src.tar.xz{,.sig})
+sha256sums=('908bce97be0275943414b45af2e2b20e8f6d5d9266fdc120bd59f096ebc547ad'
+            'SKIP'
+            'e364f135fa14c343d70cac96f577f44e8e20bf026682f647f8c3c5687a0bebd1'
+            'SKIP'
+            '8d09dc219cdb3da7dafd2161836aacdd6e02c1a113498ab5f37688599406dc8a'
+            'SKIP')
+validpgpkeys=('474E22316ABF4785A88C6E8EA2C794A986419D8A'  # Tom Stellard <tstellar@redhat.com>
+              'D574BD5D1D0E98895E3BF90044F2485E45D59042'  # Tobias Hieta <tobias@hieta.se>
+              'FFB3368980F3E6BB5737145A316C56D064CACBA5'  # Douglas Yung <douglas.yung@sony.com>
+              '71046D1E9C6656BDD61171873E83BABF4A4F9E85'  # Cullen Rhodes <cullen.rhodes@arm.com>
+)
+
+# Utilizing LLVM_DISTRIBUTION_COMPONENTS to avoid
+# installing static libraries; inspired by Gentoo
+_get_distribution_components() {
+  local target
+  ninja -t targets | grep -Po 'install-\K.*(?=-stripped:)' | while read -r target; do
+    case $target in
+      llvm-libraries|distribution)
+        continue
+        ;;
+      # shared libraries
+      LLVM|LLVMgold)
+        ;;
+      # libraries needed for clang-tblgen
+      LLVMDemangle|LLVMSupport|LLVMTableGen)
+        ;;
+      # used by lldb
+      LLVMDebuginfod)
+        ;;
+      # testing libraries
+      LLVMTestingAnnotations|LLVMTestingSupport)
+        ;;
+      # exclude static libraries
+      LLVM*)
+        continue
+        ;;
+      # exclude llvm-exegesis (doesn't seem useful without libpfm)
+      llvm-exegesis)
+        continue
+        ;;
+    esac
+    echo $target
+  done
+}
 
 prepare() {
-  cd "$srcdir"
-  rename -v -- "-$pkgver.src" '' {cmake,third-party}-"$pkgver".src
-  mkdir -p "llvm-$pkgver.src/build"
+  rename -v -- "-$pkgver.src" '' {cmake,third-party}-$pkgver.src
+  cd llvm-$pkgver.src
+  mkdir build
+
+  # Remove CMake find module for zstd; breaks if out of sync with upstream zstd
+  rm cmake/modules/Findzstd.cmake
 }
 
 build() {
-  cd "llvm-$pkgver.src/build"
-  export CC=clang CXX=clang++ AR=llvm-ar NM=llvm-nm RANLIB=llvm-ranlib \
-    LDFLAGS+=' -Wl,-O3,--sort-common,--as-needed -Wl,--gc-sections -Wl,-z,pack-relative-relocs'
-  declare -a cmake_args=(
-    -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_INSTALL_RPATH=YES
-    -DCMAKE_INSTALL_PREFIX=/usr -DLLVM_HOST_TRIPLE="$CHOST" -DLLVM_BINUTILS_INCDIR=/usr/include
-    -DLLVM_ENABLE_BINDINGS=OFF -DLLVM_INCLUDE_BENCHMARKS=OFF
-    -DLLVM_INSTALL_UTILS=ON -DPACKAGE_BUGREPORT='https://github.com/Ven0m0/PKG/issues'
+  cd llvm-$pkgver.src/build
+
+  # Build only minimal debug info to reduce size
+  CFLAGS=${CFLAGS/-g /-g1 }
+  CXXFLAGS=${CXXFLAGS/-g /-g1 }
+
+  # Add fno-semantic-position, can improve at fPIC compiled packages massively the performance
+  # At clang it improves for 3%
+  # If clang is as compiler used, it should as default add this anyways
+  export CFLAGS+=" -fno-semantic-interposition"
+  export CXXFLAGS+=" -fno-semantic-interposition"
+
+  local cmake_args=(
+    -G Ninja
+    -DCMAKE_BUILD_TYPE=Release
+    -DCMAKE_INSTALL_DOCDIR=share/doc
+    -DCMAKE_INSTALL_PREFIX=/usr
+    -DCMAKE_SKIP_RPATH=ON
+    -DLLVM_BINUTILS_INCDIR=/usr/include
+    -DLLVM_BUILD_DOCS=ON
+    -DLLVM_BUILD_LLVM_DYLIB=ON
+    -DLLVM_BUILD_TESTS=ON
+    -DLLVM_ENABLE_BINDINGS=OFF
+    -DLLVM_ENABLE_CURL=ON
+    -DLLVM_ENABLE_FFI=ON
+    -DLLVM_ENABLE_RTTI=ON
+    -DLLVM_ENABLE_SPHINX=ON
+    -DLLVM_HOST_TRIPLE=$CHOST
+    -DLLVM_INCLUDE_BENCHMARKS=OFF
+    -DLLVM_INSTALL_GTEST=ON
+    -DLLVM_INSTALL_UTILS=ON
+    -DLLVM_LINK_LLVM_DYLIB=ON
+    -DLLVM_USE_PERF=ON
+    -DSPHINX_WARNINGS_AS_ERRORS=OFF
+    -DPACKAGE_BUGREPORT=https://gitlab.archlinux.org/archlinux/packaging/packages/llvm/-/issues
   )
-  case "$_build_profile" in
-  nano | mini)
-    export CFLAGS+=' -Oz' CXXFLAGS+=' -Oz'
-    cmake_args+=(
-      -DCMAKE_BUILD_TYPE=MinSizeRel -DLLVM_BUILD_DOCS=OFF -DLLVM_BUILD_TESTS=OFF
-      -DLLVM_ENABLE_ASSERTIONS=OFF -DLLVM_ENABLE_RTTI=OFF -DLLVM_ENABLE_CURL=OFF
-      -DLLVM_ENABLE_FFI=OFF -DLLVM_ENABLE_SPHINX=OFF -DLLVM_ENABLE_UNWIND_TABLES=OFF
-    )
-    if [[ $_build_profile == 'nano' ]]; then
-      local targets=$([[ $CARCH == 'x86_64' ]] && echo 'X86;AMDGPU' || echo 'AArch64;AMDGPU')
-      cmake_args+=("-DLLVM_TARGETS_TO_BUILD=$targets")
-    fi
-    ;;
-  pgo | release)
-    export CFLAGS+=' -fno-semantic-interposition' CXXFLAGS+=' -fno-semantic-interposition'
-    cmake_args+=(
-      -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_INSTALL_DOCDIR=share/doc -DLLVM_BUILD_DOCS=OFF
-      -DLLVM_BUILD_LLVM_DYLIB=ON -DLLVM_LINK_LLVM_DYLIB=ON -DLLVM_BUILD_TESTS=OFF
-      -DLLVM_ENABLE_CURL=ON -DLLVM_ENABLE_FFI=ON -DLLVM_ENABLE_RTTI=ON
-      -DLLVM_ENABLE_SPHINX=ON -DLLVM_INSTALL_GTEST=OFF -DLLVM_USE_PERF=ON
-      -DSPHINX_WARNINGS_AS_ERRORS=OFF
-    )
-    ;;
-  esac
-  if [[ $_build_profile == 'pgo' ]]; then
-    msg 'Starting PGO generate build...'
-    cmake .. "${cmake_args[@]}" -DLLVM_BUILD_INSTRUMENTED=IR -DLLVM_VP_COUNTERS_PER_SITE=6
-    cmake --build . -j"$(nproc)"
-    ./bin/llvm-lit -v test || :
-    llvm-profdata merge -o llvm.profdata profiles/*.profraw
-    rm -rf ./* # Clean build dir for second pass
-    msg "Starting final build (PGO-use)..."
-    export CFLAGS+=" -fprofile-use=$PWD/llvm.profdata"
-    export CXXFLAGS+=" -fprofile-use=$PWD/llvm.profdata"
-    export LDFLAGS+=' -flto=full'
-    cmake_args+=(-DLLVM_ENABLE_LTO=Full -DLLVM_PROFDATA_FILE="$PWD/llvm.profdata")
-  else
-    msg "Starting final build ($_build_profile)..."
-  fi
+
+  export AR=llvm-ar
+  export CC=clang
+  export CXX=clang++
+  export NM=llvm-nm
+  export RANLIB=llvm-ranlib
+  # Export Original CFLAGS
+  export ORIG_CFLAGS="${CFLAGS}"
+  export ORIG_CXXFLAGS="${CXXFLAGS}"
+
+  export CFLAGS+=" -fprofile-generate"
+  export CXXFLAGS+=" -fprofile-generate"
+
   cmake .. "${cmake_args[@]}"
-  cmake --build . -j"$(nproc)"
+  local distribution_components=$(_get_distribution_components | paste -sd\;)
+  test -n "$distribution_components"
+  cmake_args+=(-DLLVM_DISTRIBUTION_COMPONENTS="$distribution_components")
+
+  # Build LLVM with -fprofile generate
+  cmake .. -DCMAKE_BUILD_TYPE=Release -DLLVM_BUILD_INSTRUMENTED=IR -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DLLVM_USE_LINKER=lld -DLLVM_VP_COUNTERS_PER_SITE=6 "${cmake_args[@]}"
+  ninja
+
+  # Run LLVM lit tests to generate profile to be used for PGO
+  ./bin/llvm-lit -v test || true
+
+  # Merge the generated profile
+  llvm-profdata merge -o llvm.profdata "${srcdir}/llvm-$pkgver.src/build/profiles"/*.profraw
+
+  # Use Original CFLAGS again and enable ThinLTO + use the profile
+  export PGO_PROFILE="${srcdir}/llvm-$pkgver.src/build/llvm.profdata"
+  export CFLAGS="${ORIG_CFLAGS} -fprofile-use=$PGO_PROFILE"
+  export CXXFLAGS="${ORIG_CXXFLAGS} -fprofile-use=$PGO_PROFILE"
+  export LDFLAGS="$LDFLAGS -flto=thin"
+
+  cd ..
+  mkdir build-pgo-use
+  cd build-pgo-use
+  # Enable ThinLTO
+  cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DLLVM_USE_LINKER=lld -DLLVM_ENABLE_LTO=Thin -DLLVM_PROFDATA_FILE=$PGO_PROFILE "${cmake_args[@]}"
+  ninja
+
+  # Include lit for running lit-based tests in other projects
+  pushd ../utils/lit
+  python -m build --wheel --no-isolation
+  popd
 }
+
 check() {
-  [[ $_build_profile =~ (nano|mini) ]] && return 0
-  (cd "llvm-$pkgver.src/build" && LD_LIBRARY_PATH="$PWD/lib" cmake --build . --target check)
+  cd llvm-$pkgver.src/build-pgo-use
+  LD_LIBRARY_PATH=$PWD/lib ninja check
 }
+
 package_llvm() {
-  pkgdesc='Compiler infrastructure'
-  cd "llvm-$pkgver.src/build"
-  DESTDIR="$pkgdir" cmake --install .
-  if [[ $_build_profile == 'pgo' && -x "/usr/bin/generate_propeller_profiles" ]]; then
-    msg 'Running Propeller post-link optimization...'
-    local bin_dir="$pkgdir/usr/bin"
-    find "$bin_dir" -type f -executable -print0 | while IFS= read -r -d '' bin_file; do
-      [[ $(file -b "$bin_file") =~ ELF.*executable ]] \
-        && generate_propeller_profiles --profile="$PWD/llvm.profdata" --binary="$bin_file" --output="$bin_file.prop" || :
-    done
-  fi
-  if [[ ! $_build_profile =~ (nano|mini) ]]; then
-    (cd ../utils/lit && python -m build --wheel --no-isolation && python -m installer --destdir="$pkgdir" dist/*.whl)
-    mv -f "$pkgdir"/usr/lib/lib{LLVM,LTO,Remarks}*.so* "$srcdir"
-    mv -f "$pkgdir"/usr/lib/LLVMgold.so "$srcdir"
-    rm -rf "$pkgdir"/usr/share/doc/llvm/html/{_sources,.buildinfo}
-  fi
-  install -Dm644 ../LICENSE.TXT "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
+  pkgdesc="Compiler infrastructure"
+  depends=('llvm-libs' 'curl' 'perl')
+
+  cd llvm-$pkgver.src/build-pgo-use
+
+  DESTDIR="$pkgdir" ninja install-distribution
+
+  # Include lit for running lit-based tests in other projects
+  pushd ../utils/lit
+  python -m installer --destdir="$pkgdir" dist/*.whl
+  popd
+
+  # The runtime libraries go into llvm-libs
+  mv -f "$pkgdir"/usr/lib/lib{LLVM,LTO,Remarks}*.so* "$srcdir"
+  mv -f "$pkgdir"/usr/lib/LLVMgold.so "$srcdir"
+
+  # Remove documentation sources
+  rm -r "$pkgdir"/usr/share/doc/llvm/html/{_sources,.buildinfo}
+
+  install -Dm644 ../LICENSE.TXT "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
 }
 
 package_llvm-libs() {
-  pkgdesc='LLVM runtime libraries'
+  pkgdesc="LLVM runtime libraries"
   depends=('gcc-libs' 'zlib' 'zstd' 'libffi' 'libedit' 'libxml2')
-  if [[ $_build_profile =~ (nano|mini) ]]; then
-    (cd "llvm-$pkgver.src/build" && DESTDIR="$pkgdir" cmake --build . --target install-LLVM-libraries)
-  else
-    provides=('libLLVM.so' 'libLTO.so' 'libRemarks.so')
-    install -d "$pkgdir/usr/lib"
-    cp -P "$srcdir"/lib{LLVM,LTO,Remarks}*.so* "$srcdir"/LLVMgold.so "${pkgdir}/usr/lib/"
-    install -d "${pkgdir}/usr/lib/bfd-plugins"
-    ln -s ../LLVMgold.so "${pkgdir}/usr/lib/bfd-plugins/LLVMgold.so"
-  fi
-  install -Dm644 "$srcdir/llvm-${pkgver}.src/LICENSE.TXT" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
+  provides=('libLLVM.so' 'libLTO.so' 'libRemarks.so')
+
+  install -d "$pkgdir/usr/lib"
+  cp -P \
+    "$srcdir"/lib{LLVM,LTO,Remarks}*.so* \
+    "$srcdir"/LLVMgold.so \
+    "$pkgdir/usr/lib/"
+
+  # Symlink LLVMgold.so from /usr/lib/bfd-plugins
+  # https://bugs.archlinux.org/task/28479
+  install -d "$pkgdir/usr/lib/bfd-plugins"
+  ln -s ../LLVMgold.so "$pkgdir/usr/lib/bfd-plugins/LLVMgold.so"
+
+  install -Dm644 "$srcdir/llvm-$pkgver.src/LICENSE.TXT" \
+    "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
 }
+
+# vim:set ts=2 sw=2 et:
+
